#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"
payments="true"

show_help() {
  echo "
    Usage: path/to/ffc-pay-core [OPTION...]
    Open services in VS Code.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
code ./ffc-tcg-customer-registry;
code ./ffc-tcg-portal;
code ./ffc-tcg-apply;
code ./ffc-tcg-eligibility;
code ./ffc-tcg-back-office;
code ./ffc-tcg-abaco-agri-stub;
code ./ffc-tcg-api-gateway;
